/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Bartek
 */
public class JPanelMain extends javax.swing.JPanel {

    
    private final byte size;
    private boolean sign;
    private byte place;
    /**
     * Creates new form JPanelMain
     */
    public JPanelMain() {
        size = 75;
        sign = false;
        place = 0;
        initComponents();
    }
    
    @Override
    public void paint(Graphics g){
        g.setColor(Color.black);
        
        g.fillRect(0, 0, 3 * 77, 3 * 77);
        
        g.setColor(Color.white);
        for(int i = 0; i < 3; i++) {
            for(int j = 0; j < 3; j++) {                
                g.fillRect(i * size+5, j * size+5, size-5, size-5);
            }
        } 
        g.setColor(Color.red);
        g.drawLine(31, 31, 60, 60);
        //g.setColor(Color.green);
        //for(int i = 0; i < 3; i++) {
        //    for(int j = 0; j < 3; j++) {                
        //        if(Character.getNumericValue(this.permutation.charAt(j) - 1) == i)
        //            g.fillRoundRect(i * size, j * size, size, size, 100, 100);
        //    }
        //}
    }
    
    @Override
    public void update(Graphics g){
        g.setColor(Color.pink);

        g.drawLine(100, 100, 200, 200);
        super.paint(g);
        sign = !sign;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("x");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        place = 0;

    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
