/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aitask1.Forms;

import aitask1.Classes.HetmansProblemSolver;
import aitask1.Classes.PermutationGenerator;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bartek
 */
public class JPanelMain extends javax.swing.JPanel {

    
    private final DefaultListModel<String> listModel;
    private final DefaultListModel<String> listModel2;
    
    /**
     * Creates new form JPanelMain
     */
    public JPanelMain() {
        listModel = new DefaultListModel<>();
        listModel2 = new DefaultListModel<>();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenerateMethod = new javax.swing.ButtonGroup();
        jButtonGenerate = new javax.swing.JButton();
        jLabelNumbers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGenerate = new javax.swing.JList<>();
        jComboBoxNumbers = new javax.swing.JComboBox<>();
        jRadioButtonMethodRecursion = new javax.swing.JRadioButton();
        jRadioButtonMethodLexicographically = new javax.swing.JRadioButton();
        jLabelGenerateMethod = new javax.swing.JLabel();
        jCheckBoxValidResults = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        dupa = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButtonGenerate.setText("Generate!");
        jButtonGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGenerateMouseClicked(evt);
            }
        });

        jLabelNumbers.setText("Type n:");

        jListGenerate.setModel(listModel);
        jScrollPane1.setViewportView(jListGenerate);

        jComboBoxNumbers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        buttonGroupGenerateMethod.add(jRadioButtonMethodRecursion);
        jRadioButtonMethodRecursion.setSelected(true);
        jRadioButtonMethodRecursion.setText("recursion");

        buttonGroupGenerateMethod.add(jRadioButtonMethodLexicographically);
        jRadioButtonMethodLexicographically.setText("lexicographically");

        jLabelGenerateMethod.setText("Generate method:");

        jCheckBoxValidResults.setText("8 hetmans problem solve");

        dupa.setModel(listModel2);
        jScrollPane2.setViewportView(dupa);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGenerateMethod)
                            .addComponent(jLabelNumbers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonMethodRecursion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMethodLexicographically))
                            .addComponent(jComboBoxNumbers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxValidResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumbers)
                    .addComponent(jComboBoxNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxValidResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGenerateMethod)
                        .addComponent(jRadioButtonMethodRecursion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMethodLexicographically)
                        .addComponent(jButtonGenerate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGenerateMouseClicked
        
        ArrayList<String> result = new ArrayList<>();
        
        //clear listBox
        listModel.removeAllElements();
        listModel2.removeAllElements();
        
        try {            
            if(jRadioButtonMethodRecursion.isSelected()) {//recursive
               //build n size string from 0 to n
                String source = "";
                int i = 1;
                while(i <= Integer.parseInt(jComboBoxNumbers.getSelectedItem().toString())) {
                    source += i;
                    i++;
                }      
                //calculate
                result = PermutationGenerator.GeneratePermutationRecursive(source);     
            }
            else {//lexicographically
                //calculate
                result = PermutationGenerator.GeneratePermutationLexicographically(Integer.parseInt(jComboBoxNumbers.getSelectedItem().toString()));              
            } 
            //show results
            int counter2 = 0;
            for(String permutation: result) {
                listModel.addElement(permutation);
                counter2++;
            }    
            jLabel2.setText(String.valueOf(counter2));
            if(jCheckBoxValidResults.isSelected()) {//8 hetmans problem solve
                ArrayList<String> result2 = HetmansProblemSolver.validPermutations(result);
                //show results
                int counter = 0;
                for(String permutation: result2) {
                    counter ++;
                    listModel2.addElement(permutation);
                } 
                jLabel1.setText(String.valueOf(counter));
            }
        }
        catch(NumberFormatException exc) {
            JOptionPane.showMessageDialog(null, "whaaaat?" + exc.toString());
        }
        catch(Exception exc) {
            JOptionPane.showMessageDialog(null, "whaaaaaaaat?" + exc.toString());
        } 
    }//GEN-LAST:event_jButtonGenerateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenerateMethod;
    private javax.swing.JList<String> dupa;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JCheckBox jCheckBoxValidResults;
    private javax.swing.JComboBox<String> jComboBoxNumbers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGenerateMethod;
    private javax.swing.JLabel jLabelNumbers;
    private javax.swing.JList<String> jListGenerate;
    private javax.swing.JRadioButton jRadioButtonMethodLexicographically;
    private javax.swing.JRadioButton jRadioButtonMethodRecursion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
