/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aitask1.Forms;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Bartek
 */
public class JPanelDrawChessboard extends javax.swing.JPanel {

    /**
     * @return the permutation
     */
    public String getPermutation() {
        return permutation;
    }

    private final String permutation;
    private final int number;
    /**
     * Creates new form JPanelDrawChessboard
     * @param permutation
     */
    public JPanelDrawChessboard(String permutation) {
        this.permutation = permutation;
        this.number = permutation.length();
        initComponents();
    }
    
    @Override
    public void paint(Graphics g){
        g.setColor(Color.black);
        
        int size = 50;
        
        for(int i = 0; i < number; i++) {
            for(int j = 0; j < number; j++) {
                if((i + j) % 2 == 0) {
                    g.setColor(Color.black);
                    g.fillRect(i * size, j * size, size, size);
                }
                else {
                    g.setColor(Color.white);
                    g.fillRect(i * size, j * size, size, size);
                
                }
            } 
        }
        g.setColor(Color.green);
        for(int i = 0; i < number; i++) {
            for(int j = 0; j < number; j++) {                
                if(Character.getNumericValue(this.getPermutation().charAt(j) - 1) == i)
                    g.fillRoundRect(i * size, j * size, size, size, 100, 100);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
